module.exports = {
    ...require('./AddAgentPage'),
    ...require('./ManageAgentsPage'),
    ...require('./AgentOnboardingPage'),
    ...require('./McStaffPage'),
    ...require('./TeamPage'),
    ...require('./TagPage'),
    ...require('./ManageFormsPage'),
    ...require('./EmailNotification Page'),
    ...require('./TrainingNvideosPage'),
    ...require('./DashboardPage'),
    ...require('./AgentRosterPage'),
    ...require('./BulkTaskPage'),
    ...require('./HundredDayChecklistPage'),
    ...require('./DailySnapshotPage'),
    ...require('./DatabaseDashboardPage'),
    ...require('./DocumentLibraryPage'),
    ...require('./CalendarPage'),
    ...require('./ChecklistPage'),
    ...require('./checklistDashboardPage'),
};
